name: verbose
description: A tiny Dart debugging utility package for verbosely logging message.
version: 0.1.0
homepage: https://github.com/hyiso/verbose

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
